name: CustomBP
version: '${project.version}'
main: mc.custombattlepass.org.custombp.CustomBP
api-version: 1.16
authors: [ san1rope ]
description: Custom Battle Pass for minecraft 1.16.5
softdepend: [PlaceholderAPI]
commands:
  pass: { }
